# Thanks to the Code Spell Checker team for the example workflow
name: SpellCheck
on: [push]
jobs:
  SpellCheck:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          skip: "*.svg,*git,*result*,*yml"
